### ISSUE TITLE
Exception with 2.0.0-rc6?

### ISSUE THREAD

**Issue by sparkofreason** [martinklepsch/boot-deps#3]
Got the output below after latest boot -u:
```
Searching for outdated dependencies...
             clojure.lang.ExceptionInfo: java.lang.RuntimeException: No such namespace: util, compiling:(NO_SOURCE_PATH:0:0)
    data: {:file "../tmp/boot.user6056438542821412817.clj", :line 15}
java.util.concurrent.ExecutionException: java.lang.RuntimeException: No such namespace: util, compiling:(NO_SOURCE_PATH:0:0)
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: util, compiling:(NO_SOURCE_PATH:0:0)
             java.lang.RuntimeException: No such namespace: util
                                ...                                        
                  clojure.core/eval                          core.clj: 2927
                  boot.pod/eval-in*                           pod.clj:  203
                                ...                                        
                  boot.pod/eval-in*                           pod.clj:  206
          boot-deps/eval66/fn/fn/fn                     boot_deps.clj:   22
                boot.core/run-tasks                          core.clj:  618
                                ...                                        
              boot.user/eval2034/fn  boot.user6056438542821412817.clj:   17
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
                                ...                                      
```

**Comment by martinklepsch** [comment]
Can't really correlate the error and the fix but I encountered the same issue on RC6 and this fixed it: https://github.com/martinklepsch/boot-deps/commit/8dcd2dea513a31ecbd88022a352fed871d3628e1

Close if that works for you as well :+1:

**Comment by sparkofreason** [comment]
Hi. Thanks for the quick turnaround. It did work to simply refer to 0.1.3, I had to clone and build/install locally. Is that expected?

**Comment by martinklepsch** [comment]
Huh, no. That's unexpected.

**Comment by martinklepsch** [comment]
If anyone encounters this or wants to help:
```
boot -d boot-deps ancient
```
this will download the most recent version and run the ancient task.

**Comment by micha** [comment]
@sparkofreason The reason why cloning and building from source fixed the problem for you is because that commit included a change to the java binary. See https://github.com/boot-clj/boot/releases/tag/2.0.0-rc6. Downloading the latest binary release would fix it.

**Comment by sparkofreason** [comment]
@micha Just to make sure I understand: boot -u is not sufficient to update to rc6, need to get the latest version of boot.sh?

**Comment by micha** [comment]
@sparkofreason `boot -u` updates everything but the executable, which you must download separately.
