### ISSUE TITLE
ignore snapshots

### ISSUE THREAD

**Issue by stephanos** [martinklepsch/boot-deps#4]
It would be great if you would allow ignoring snapshot version :)

**Comment by martinklepsch** [comment]
Reading the [anceint-clj documentation](https://github.com/xsc/ancient-clj#artifacts--options) this seems fairly easy to do.
Would you be willing to provide a PR? :)

**Comment by stephanos** [comment]
I could give it a try tomorrow.

**Comment by stephanos** [comment]
@martinklepsch how do you run a forked boot-deps plugin locally?

**Comment by martinklepsch** [comment]
@stephanos you can just build and install a new jar with the `build-jar` command.
If you compose it with the `watch` task it will be reinstalled whenever you change source files:
```
boot watch build-jar
```

**Comment by stephanos** [comment]
@martinklepsch well, this is what I have so far: https://github.com/stephanos/boot-deps/commit/dfde973dc1cfb5ec58320c0961d7f1a380b6098f 

I get the error 'Unable to resolve symbol: opts in this context'. Not sure how to fix this. Looks like a macro (?), never wrote one before.

**Comment by martinklepsch** [comment]
@stephanos Thank you! :tada: I think that's it basically. I added a few comments to the commit you linked. If you create a PR I can merge it :+1:

**Comment by stephanos** [comment]
@martinklepsch thanks for the pointers, seems to work now :)
